### ISSUE TITLE
Skipping every second frame?

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [TemugeB/bodypose3d#10]
Hi, Small doubt about the show_3d_pose.py file. Why are you skipping every second frame? how to save the 3D output to animation?

**Comment by TemugeB** [comment]
The code is using matplotlib to draw the pose. It is unfortunately slow. So I skip every second frame to show the motion data faster. If you need to see every frame, you can modify the code as you need.

**Comment by AkhilaPerumalla123** [comment]
Hi TemugeB, can you help me to save this 3D output to animation or some video output?

**Comment by TemugeB** [comment]
Are you on windows, linux or mac?

Basically just save the figures to disk. Create a folder named ```figures```. Then add this line 
```python
plt.savefig('figures/' + str(framenum).zfill(3) + '.png')
```
before or after line [66](https://github.com/TemugeB/bodypose3d/blob/4d505a50f9ae9d2b36326ea37de001f390b32b04/show_3d_pose.py#L66).

Then go into the figures folder and run:
```
ffmpeg -framerate 20 -i %03d.png output.mp4
```
This is done in linux. You can also just google how to convert images to video on your operating system.
