### ISSUE TITLE
camera synchronization

### ISSUE THREAD

**Issue by enrico310786** [TemugeB/bodypose3d#13]
Hi,
could you give me some suggestions or tools to synchronize the two webcams that record videos from two different angles. 
Many thanks in advance!

**Comment by TemugeB** [comment]
Check this package: [python_stereo_calibrate](https://github.com/TemugeB/python_stereo_camera_calibrate). Please try not to open to many general questions in the issues. Use the previous issue for further questions. I will close this issue for now.
