### ISSUE TITLE
Two cameras' calibration with two rotation matrix?

### ISSUE THREAD

**Issue by ligaoqi2** [TemugeB/bodypose3d#19]
Amazing work! I wonder why there are two different rotation matrix and translation matrix in folder camera_parameters?Shouldn't the binocular camera calibration only have a rotation matrix and a translation matrix to represent the pose between the two cameras?

**Comment by TemugeB** [comment]
If you want to use one of the cameras as the center of your coordinate system, then yes, you only need one transformation from camera1 to camera2. But if you want to define coordinate system away from the cameras, then you need two. So one transform to define coordinate system origin to camera1 and another transform from camera1 to camera2.

**Comment by ligaoqi2** [comment]
Ok, thank you so much~

**Comment by ligaoqi2** [comment]
Excuse me~I also want to ask you, if a camera is the center, what does its rotation matrix look like? Is it the identity matrix? Is the translation matrix [0.0, 0.0, 0.0]?

**Comment by TemugeB** [comment]
Yes, identity rotation and 0 translation.

**Comment by ligaoqi2** [comment]
Thanks very much～I have done with satisfactory result.

Temuge Batpurev ***@***.***> 于 2023年5月24日周三 13:41写道：

**Comment by TemugeB** [comment]
Glad I could help. I will close this issue. But in general, please close issues that you create on github.
