### ISSUE TITLE
Index vs. body points meaning is not clear

### ISSUE THREAD

**Issue by valioiv** [TemugeB/bodypose3d#7]
Sorry for opening an issue it this repo but not sure where to ask...
I'm reading your tutorial about how to calibrate camera and I'm not clear what is the mapping between index of this array and the body parts... For example index 0 of `uvs1` list (content `[458, 86]`) is nose, or the left eye, or what? Can you briefly enumerate them? I can see 12 body point.

![image](https://user-images.githubusercontent.com/25353306/172862604-2af94248-6492-4a42-af79-bcf5e9cc6088.png)

**Comment by TemugeB** [comment]
I don't remember which points correspond to which body parts. However, it is important that the same body point is indexed by the same value in both camera views. One easy way to check the indices is to write:
```python
plt.imshow(frame1[:,:,[2,1,0]])
plt.scatter(uvs1[:,0], uvs1[:,1])
for i, uv in enumerate(uvs1):
   plt.text(uv[0], uv[1], str(i))
plt.show()
```
This should put the indices on each keypoint.

**Comment by valioiv** [comment]
Thank you so much for your support! I made it as you suggested and figured-out what I needed!
