### ISSUE TITLE
Can we implement this for recorded videos as well?

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [TemugeB/bodypose3d#9]
Hi, I want to implement this for recorded videos using multiple cameras. Is it possible to do that?

**Comment by TemugeB** [comment]
Yes. Actually if you just run the code it performs 3D triangulation from examples videos included in this repository. Read the code and see what is going on. All you have to do is replace the video file names and replace the camera calibration parameters. If you need to calibrate the cameras, go to my other repository here: [link](https://github.com/TemugeB/python_stereo_camera_calibrate) .

**Comment by TemugeB** [comment]
If you recorded the videos already and moved the cameras, then unfortunately there is no way to obtain global 3D coordinates. You can try single camera depth estimation in the mediapipe results. But these will be relative 3D coordinates. Also, I'm not sure what it is relative to.

**Comment by AkhilaPerumalla123** [comment]
Thanks, @TemugeB, I will try first try to implement with example videos.
